name: Build and run contract unit tests

on:
  pull_request:
    branches:
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
            node-version: 16.x
      - name: Clean cache and node modules
        run: |
          rm -rf node_modules 
          rm -f package-lock.json
          rm -f yarn.lock
      - name: Install dependencies
        run: npm install
      - name: Compile and Unit test contracts
        run: npm run test